import type { NavigationDefinition } from './navigation.registry.js';

/**
 * Menú sembrado por las migraciones, tal como queda tras 1767225740000 (íconos, /imports, /handovers y
 * /document-templates → /documents). La app no lo lee: el menú real vive en navigation_item. Solo sirve de catálogo
 * de fixture a los specs de autorización, que deben describir el menú que existe.
 */
export const DEFAULT_NAVIGATION_ITEMS: ReadonlyArray<NavigationDefinition> = [
  {
    module: 'USER',
    moduleLabel: 'Administración',
    resource: 'user',
    path: '/users',
    label: 'Usuarios',
    requiredAction: 'read',
    sortOrder: 10,
    icon: 'users',
  },
  {
    module: 'USER',
    moduleLabel: 'Administración',
    resource: 'role',
    path: '/roles',
    label: 'Roles y permisos',
    requiredAction: 'read',
    sortOrder: 20,
    icon: 'shield',
  },
  {
    module: 'STRUCTURE',
    moduleLabel: 'Estructura',
    resource: 'campus',
    path: '/campus',
    label: 'Campus y ubicaciones',
    requiredAction: 'read',
    sortOrder: 30,
    icon: 'map-pinned',
  },
  {
    module: 'STRUCTURE',
    moduleLabel: 'Estructura',
    resource: 'org_unit',
    path: '/organizational-units',
    label: 'Organigrama',
    requiredAction: 'read',
    sortOrder: 40,
    icon: 'landmark',
  },
  {
    module: 'STRUCTURE',
    moduleLabel: 'Estructura',
    resource: 'cost_center',
    path: '/cost-centers',
    label: 'Centros de costo',
    requiredAction: 'read',
    sortOrder: 50,
    icon: 'wallet',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'category',
    path: '/categories',
    label: 'Categorías',
    requiredAction: 'read',
    sortOrder: 60,
    icon: 'tags',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'asset',
    path: '/assets',
    label: 'Activos',
    requiredAction: 'read',
    sortOrder: 70,
    icon: 'package',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'asset',
    path: '/imports',
    label: 'Importar desde Excel',
    requiredAction: 'create',
    sortOrder: 72,
    icon: 'file-spreadsheet',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'asset',
    path: '/handovers',
    label: 'Entregas de activos',
    requiredAction: 'read',
    sortOrder: 74,
    icon: 'package-check',
  },
  {
    module: 'INVENTORY',
    moduleLabel: 'Inventarios',
    resource: 'physical_inventory',
    path: '/inventories',
    label: 'Tomas físicas',
    requiredAction: 'read',
    sortOrder: 75,
    icon: 'clipboard-check',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'loan',
    path: '/loans',
    label: 'Préstamos',
    requiredAction: 'read',
    sortOrder: 80,
    icon: 'handshake',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'depreciation',
    path: '/depreciation',
    label: 'Depreciación',
    requiredAction: 'read',
    sortOrder: 85,
    icon: 'calculator',
  },
  {
    module: 'ASSET',
    moduleLabel: 'Activos',
    resource: 'document_template',
    path: '/documents',
    label: 'Documentos',
    requiredAction: 'read',
    sortOrder: 90,
    icon: 'file-text',
  },
  {
    module: 'SYSTEM',
    moduleLabel: 'Sistema',
    resource: 'storage',
    path: '/storage',
    label: 'Almacenamiento',
    requiredAction: 'update',
    sortOrder: 100,
    icon: 'hard-drive',
  },
  {
    module: 'SYSTEM',
    moduleLabel: 'Sistema',
    resource: 'mail',
    path: '/mail',
    label: 'Correo',
    requiredAction: 'manage',
    sortOrder: 105,
    icon: 'circle',
  },
  {
    module: 'SYSTEM',
    moduleLabel: 'Sistema',
    resource: 'feature',
    path: '/features',
    label: 'Módulos',
    requiredAction: 'manage',
    sortOrder: 110,
    icon: 'panels-top-left',
  },
  {
    module: 'SYSTEM',
    moduleLabel: 'Sistema',
    resource: 'navigation',
    path: '/navigation',
    label: 'Menús',
    requiredAction: 'manage',
    sortOrder: 120,
    icon: 'list-tree',
  },
];
