export const DATA_QUALITY_FLAGS = [
  'BARCODE_TEMP',
  'BARCODE_DUPLICATED',
  'BARCODE_EMPTY',
  'ACQUISITION_DATE_MISSING',
  'ACQUISITION_DATE_INVALID',
  'PHOTO_MISSING',
  'PRICE_ZERO',
  'PRICE_MISSING',
  'CATEGORY_UNASSIGNED',
  'ACQUISITION_TYPE_UNKNOWN',
  'PHYSICAL_CONDITION_UNKNOWN',
  'COST_CENTER_NOT_IN_CATALOG',
] as const;

export type DataQualityFlag = (typeof DATA_QUALITY_FLAGS)[number];
